---
name: Storable-AMF
version: 0.52
author: []
abstract: Perl extension for serialize/deserialize AMF0/AMF3 data
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  XSLoader: 0
  perl: 5.8.0
build_requires:
  ExtUtils::CBuilder: 0.15
  ExtUtils::ParseXS: 0
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.21
  Test::More: 0
dynamic_config: 0
provides:
  Storable::AMF:
    file: lib/Storable/AMF.pm
    version: 0.52
  Storable::AMF0:
    file: lib/Storable/AMF0.pm
    version: 0.52
  Storable::AMF0::Var:
    file: lib/Storable/AMF.pm
  Storable::AMF3:
    file: lib/Storable/AMF3.pm
    version: 0.52
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
