--- #YAML:1.0
name:               Storable-AMF
version:            0.70
abstract:           Perl extension for serialize/deserialize AMF0/AMF3 data
author:
    - Grishaev Anatoliy  <grian@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Module::Build:        0.2
    Module::Build::Compat:  0.02
    perl:                 5.008
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
