--- #YAML:1.0
name:               Storable-AMF
version:            0.89
abstract:           serializing/deserializing AMF0/AMF3 data
author:
    - Grishaev Anatoliy  <grian@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:         0
    File::Copy:  0
    perl:        5.008001
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Storable-AMF
    homepage:    http://search.cpan.org/dist/Storable-AMF
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/Grian/Storable-AMF.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
